package gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import sql.Connector;

/**
 * The ResultFrame, containing the results of the diff
 *
 * @author ahughes
 */
public class ResultFrame extends GUI {

    /**
     * Constructor
     * 
     * @param aPreviousFrame
     * @param aConnector1
     * @param aConnector2 
     */
    public ResultFrame(GUI aPreviousFrame, Connector aConnector1, Connector aConnector2) {
        pFrame = aPreviousFrame;
        c1 = aConnector1;
        c2 = aConnector2;

        initComponents();
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                back();
            }
        });
        loadResults();
        
        super.setFrameLocationCenter();
        this.setVisible(true);
    }
    
    private void loadResults() {
        
    }

    /**
     * Closes the connections and heads back to EntryFrame
     */
    private void back() {
        try {
            c1.closeConnection();
            c2.closeConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ResultFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        pFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
